<?php

declare(strict_types=1);

use App\Support\Web\WebAdminPermissions;

return [
    'enabled' => env('ADMIN_WEB_ENABLED', true),

    'template' => [
        'source' => 'https://github.com/eloicorreia/templateweb',
        'variant' => 'master',
        'asset_path' => 'vendor/templateweb/master/assets',
        'required_assets' => [
            'css/bootstrap.min.css',
            'css/icons.min.css',
            'css/icons.min.css.map',
            'css/app.min.css',
            'css/custom.min.css',
            'css/admin-contract.css',
            'js/layout.js',
            'js/pages/password-addon.init.js',
            'libs/bootstrap/js/bootstrap.bundle.min.js',
            'images/favicon.ico',
            'images/logo-dark.png',
            'images/logo-light.png',
            'images/logo-sm.png',
            'images/auth-one-bg.jpg',
            'fonts/hkgrotesk-light.eot',
            'fonts/hkgrotesk-light.woff',
            'fonts/hkgrotesk-light.woff2',
            'fonts/hkgrotesk-regular.eot',
            'fonts/hkgrotesk-regular.woff',
            'fonts/hkgrotesk-regular.woff2',
            'fonts/hkgrotesk-medium.eot',
            'fonts/hkgrotesk-medium.woff',
            'fonts/hkgrotesk-medium.woff2',
            'fonts/hkgrotesk-semibold.eot',
            'fonts/hkgrotesk-semibold.woff',
            'fonts/hkgrotesk-semibold.woff2',
            'fonts/hkgrotesk-bold.ttf',
            'fonts/hkgrotesk-bold.woff',
            'fonts/hkgrotesk-bold.woff2',
            'fonts/boxicons.eot',
            'fonts/boxicons.svg',
            'fonts/boxicons.ttf',
            'fonts/boxicons.woff',
            'fonts/boxicons.woff2',
            'fonts/la-brands-400.eot',
            'fonts/la-brands-400.svg',
            'fonts/la-brands-400.ttf',
            'fonts/la-brands-400.woff',
            'fonts/la-brands-400.woff2',
            'fonts/la-regular-400.eot',
            'fonts/la-regular-400.svg',
            'fonts/la-regular-400.ttf',
            'fonts/la-regular-400.woff',
            'fonts/la-regular-400.woff2',
            'fonts/la-solid-900.eot',
            'fonts/la-solid-900.svg',
            'fonts/la-solid-900.ttf',
            'fonts/la-solid-900.woff',
            'fonts/la-solid-900.woff2',
            'fonts/materialdesignicons-webfont.eot',
            'fonts/materialdesignicons-webfont.ttf',
            'fonts/materialdesignicons-webfont.woff',
            'fonts/materialdesignicons-webfont.woff2',
            'fonts/remixicon.eot',
            'fonts/remixicon.svg',
            'fonts/remixicon.symbol.svg',
            'fonts/remixicon.ttf',
            'fonts/remixicon.woff',
            'fonts/remixicon.woff2',
        ],
    ],

    'permissions' => WebAdminPermissions::descriptions(),

    'logs' => [
        'default_period_days' => 1,
        'max_period_days' => 31,
        'per_page' => 15,
        'max_per_page' => 50,
        'preview_text_limit' => 1000,
        'detail_text_limit' => 4000,
        'max_payload_items' => 100,
    ],
];
